# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'SampleGRWebServiceManager' do
pod 'Alamofire', '~> 1.3'
pod 'SDWebImage', '~>3.7'
end

target 'SampleGRWebServiceManagerTests' do

end

